### PR TITLE
Add searching for products

### PR DESCRIPTION
**Pull request by evfinkn**
This adds functionality for searching products. Using the search input in the navbar, you can search products' title and description. Matches in product title are ranked higher than matches in product description. Additionally,

- not every word has to be matched (e.g., searching for "apple phone" will match products containing either "apple" or "phone"),
- full words aren't needed to match (e.g., searching for "super" will match a product containing "supersized"), and
- derivative words are matched (e.g., searching for "block" will match products with "block", "blocks", "blocking", etc.).

### CODE REVIEW

**Comment by blhohmann** [comment]
I get this when I search, is the the intended functionality, is this just the backend for search with no frontend for this pull request?
image

**Comment by evfinkn** [comment]
> I get this when I search, is the the intended functionality, is this just the backend for search with no frontend for this pull request?

Yeah, I was using a local dynamic products page since we hadn't had one yet but only pushed the backend functionality for when John's stuff was merged. I'm merging main into this branch right now, so you should be able to test it when that's done.

**Comment by blhohmann** [comment]
> > I get this when I search, is the the intended functionality, is this just the backend for search with no frontend for this pull request?
> 
> Yeah, I was using a local dynamic products page since we hadn't had one yet but only pushed the backend functionality for when John's stuff was merged. I'm merging main into this branch right now, so you should be able to test it when that's done.

Perfect, thanks!

**Comment by evfinkn** [comment]
Merged, but currently doesn't support searching AND sorting. Working on a fix.

**Comment by evfinkn** [comment]
Alright, it's fixed! If you want to try it out, it might be useful to do `bin/rails runner db/seeds/search.rb`. After that, good search examples are "ipod", "ipod vintage", "vintage", "shirt", and "awesome".

**Comment by blhohmann** [comment]
Looks great! I'm going to approve, but if you get the chance maybe it could be good to add something like
```Search Results for ${search_term}``` so a user knows what they just searched like our last homework in this class

**Review by blhohmann — APPROVED** [review]
Looks good, good job.

**Pull request merged**
