### PR TITLE
Quick bug fixes

### PR DESCRIPTION
**Pull request by evfinkn**
Fixes bug with admins not being seen as sellers and bug with signup form not re-rendering when invalid.

### CODE REVIEW

**Review by blhohmann — APPROVED** [review]
Good bug fixes.

**Comment by powersaudrey25** [comment]
I logged in as one of our default admins - admin@admin.com admin000 - and even though seeds.rb sets is_seller true, I was still seeing "Register as Seller" in their dropdown. 

Doing this in _user_dropdown seemed to fix it 
`  <%= dropdown_link "Register as seller", register_path unless user.is_seller || user.is_admin %>
`
I'm not sure why it wasn't working to just check user.is_seller

**Comment by blhohmann** [comment]
> I logged in as one of our default admins - [admin@admin.com](mailto:admin@admin.com) admin000 - and even though seeds.rb sets is_seller true, I was still seeing "Register as Seller" in their dropdown.
> 
> Doing this in _user_dropdown seemed to fix it ` <%= dropdown_link "Register as seller", register_path unless user.is_seller || user.is_admin %>` I'm not sure why it wasn't working to just check user.is_seller

I'll retry as is, one sec.

**Review by powersaudrey25 — APPROVED** [review]

**Comment by blhohmann** [comment]
> > I logged in as one of our default admins - [admin@admin.com](mailto:admin@admin.com) admin000 - and even though seeds.rb sets is_seller true, I was still seeing "Register as Seller" in their dropdown.
> > Doing this in _user_dropdown seemed to fix it ` <%= dropdown_link "Register as seller", register_path unless user.is_seller || user.is_admin %>` I'm not sure why it wasn't working to just check user.is_seller
> 
> I'll retry as is, one sec.

image
It appears to work for me when I checkout

**Pull request merged**
