### PR TITLE
Price alert

### PR DESCRIPTION
**Pull request by blhohmann**
# Pull Request: Price Alerts Feature

## Description

This pull request adds price alerts for users where they will be emailed when a product's price drops below their threshold with the current price, old price, their set threshold, and a link to the product. Routes are provided for index (list of a user price alerts), show (see an individual price alerts information), edit (change the threshold for a product), delete, new (make a price alert for a product, option to do so is on a products show page).

## Changes Made

Storefront Changes:
- ICRUD for Price Alerts (only for those Price Alerts associated with the current user)
- Add price alerts to user dropdown navbar
- Add price alert email sends to a user's email when a product they have a price alert on goes lower than their threshold

General Changes:
- Add configuration for emails
- Created an email account connected to the configuration
 
### To manually test the sign-in feature:
View Price Alert links on nav bar user dropdown and try to break it.

#### To run the rspec tests put this in your terminal
``` bundle exec rspec```

## Impact on Existing Code
- No breaking changes observed

### Include but are not limited to:
Index happy path populated:
image

Index happy path empty:
image

New happy path:
image
image
image

New sad path, already have a price alert for this product for this user:
image

Edit happy path:
image
image

Delete happy path:
image
image

Price alert email happy path, the price changed lower than threshold:
image

## Additional Notes

- This feature will need to be extended to work with deals and not just with manually updating price
- No major performance issues have been observed during testing.

## Reviewer Requests

I kindly request a review of these changes. Please provide feedback and suggestions. As this was a 3 point user story just 2 reviews will be necessary.

### Controller test
96.23 %

### Overall Tests
Coverage report generated for RSpec to /mnt/c/Users/blake/selt2023-final-project-team-001/coverage. 1720 / 1796 LOC (95.77%) covered.

## Discussion

Feel free to comment, ask questions, or provide feedback.

Should be no merge conflicts with main.

### CODE REVIEW

**Comment by powersaudrey25** [comment]
Might be nice to show the old threshold on the edit page
Screenshot 2023-12-07 at 11 06 23 AM

**Comment by blhohmann** [comment]
> Might be nice to show the old threshold on the edit page Screenshot 2023-12-07 at 11 06 23 AM

Great idea, I'll add that

**Comment by powersaudrey25** [comment]
Getting 
```
PG::NotNullViolation: ERROR:  null value in column "name" of relation "storefronts" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 1, 2023-12-07 17:16:51.717354, 2023-12-07 17:16:51.717354, null, , null).
/Users/audreypowers/SELT/selt2023-final-project-team-001/db/seeds/development.rb:78:in `block in <top (required)>'
/Users/audreypowers/SELT/selt2023-final-project-team-001/db/seeds/development.rb:77:in `<top (required)>'
/Users/audreypowers/SELT/selt2023-final-project-team-001/db/seeds.rb:92:in `load'
/Users/audreypowers/SELT/selt2023-final-project-team-001/db/seeds.rb:92:in `<top (required)>'
Tasks: TOP => db:reset => db:setup => db:seed
```
This might be resolved once merge conflicts are resolved

**Comment by powersaudrey25** [comment]
Do we want sellers to have the ability to set price alerts for their own products? Right now if i create a product I can set a price alert

**Comment by powersaudrey25** [comment]
Also got some failing 

> > Do we want sellers to have the ability to set price alerts for their own products? Right now if i create a product I can set a price alert
> 
> I think either way is fine, but if you think it is better that a seller can't alert their own product I think that makes sense and I can do it.

I think logically it makes sense, but if it would take too much time to implement don't worry about it!

**Comment by powersaudrey25** [comment]
Also there are some failing tests
```
rspec ./spec/controllers/price_alerts_controller_spec.rb:108 # PriceAlertsController DELETE #destroy when the price alert belongs to the user deletes the price alert
rspec ./spec/controllers/price_alerts_controller_spec.rb:117 # PriceAlertsController DELETE #destroy when the price alert does not belong to the user redirects to the home page
rspec ./spec/controllers/price_alerts_controller_spec.rb:136 # PriceAlertsController DELETE #delete when the price alert does not belong to the user redirects to the home page
rspec ./spec/controllers/price_alerts_controller_spec.rb:147 # PriceAlertsController DELETE #destroy when the price alert belongs to the user deletes the price alert
rspec ./spec/controllers/price_alerts_controller_spec.rb:156 # PriceAlertsController DELETE #destroy when the price alert does not belong to the user redirects to the home page
rspec ./spec/controllers/price_alerts_controller_spec.rb:175 # PriceAlertsController DELETE #delete when the price alert does not belong to the user redirects to the home page
```

**Comment by blhohmann** [comment]
> Also there are some failing tests
> 
> ```
> rspec ./spec/controllers/price_alerts_controller_spec.rb:108 # PriceAlertsController DELETE #destroy when the price alert belongs to the user deletes the price alert
> rspec ./spec/controllers/price_alerts_controller_spec.rb:117 # PriceAlertsController DELETE #destroy when the price alert does not belong to the user redirects to the home page
> rspec ./spec/controllers/price_alerts_controller_spec.rb:136 # PriceAlertsController DELETE #delete when the price alert does not belong to the user redirects to the home page
> rspec ./spec/controllers/price_alerts_controller_spec.rb:147 # PriceAlertsController DELETE #destroy when the price alert belongs to the user deletes the price alert
> rspec ./spec/controllers/price_alerts_controller_spec.rb:156 # PriceAlertsController DELETE #destroy when the price alert does not belong to the user redirects to the home page
> rspec ./spec/controllers/price_alerts_controller_spec.rb:175 # PriceAlertsController DELETE #delete when the price alert does not belong to the user redirects to the home page
> ```

I get 0 failures, could you try running rspec after bin/rails db:reset and let me know if you get 0 failures then

**Comment by powersaudrey25** [comment]
Okay yeah that was my bad with the tests they all pass now. However after adding in those last two commits Create a Price Alert is now broken and does a 404, product_id is still getting passed through though
```
ActiveRecord::RecordNotFound (Couldn't find Product without an ID):
  
app/controllers/price_alerts_controller.rb:23:in `create'
Processing by ErrorsController#not_found as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "price_alert"=>{"product_id"=>"6", "new_threshold"=>"5.00"}, "commit"=>"Create Price Alert"}
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 36], ["LIMIT", 1]]

```

**Comment by blhohmann** [comment]
> Okay yeah that was my bad with the tests they all pass now. However after adding in those last two commits Create a Price Alert is now broken and does a 404, product_id is still getting passed through though
> 
> ```
> ActiveRecord::RecordNotFound (Couldn't find Product without an ID):
>   
> app/controllers/price_alerts_controller.rb:23:in `create'
> Processing by ErrorsController#not_found as TURBO_STREAM
>   Parameters: {"authenticity_token"=>"[FILTERED]", "price_alert"=>{"product_id"=>"6", "new_threshold"=>"5.00"}, "commit"=>"Create Price Alert"}
>   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 36], ["LIMIT", 1]]
> ```

Hmm I don't remember that on my end. I'll look into it later tonight I'm away for a bit, thanks.

**Review by powersaudrey25 — APPROVED** [review]
Working as expected, tests all passing. Great work, thanks!

**Review by kesslerjohn — APPROVED** [review]
Everything is working as expected. Great work!

**Pull request merged**
